# .github/workflows/mirror.yml
name: Mirror to Other Repositories

on:
  push:
    branches:
      - main  # Or replace with your primary branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Mirror to PDG repo
        env:
          TOKEN: ${{ secrets.SecondLevelBigStatsDataProducts_PDG }}
        run: |
          git config --global user.name "Xiao-Chen820"
          git config --global user.email "xiaochen82028@gmail.com"
          git remote add pdg https://x-access-token:${TOKEN}@github.com/PermafrostDiscoveryGateway/SecondLevelBigStatsDataProducts_PDG.git
          git push --force pdg main

      - name: Mirror to personal repo
        env:
          TOKEN: ${{ secrets.SecondLevelBigStatsDataProducts-Personal }}
        run: |
          git remote add personal https://x-access-token:${TOKEN}@github.com/https://github.com/Xiao-Chen820/Second-level-Big-Stats-Data-Products.git
          git push --force personal main
